# Generated by Django 3.2.5 on 2021-08-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_user_solution_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='user',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='user',
        ),
        migrations.AddField(
            model_name='application',
            name='user_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='problem',
            name='user_name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
