# Generated by Django 3.2.5 on 2021-08-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_application_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
